---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ ghost_namespace }}"
  name: ghost-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi