---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        env:
          - name: NODE_ENV
            value: "production"
          - name: url
            value: "http://{{ ghost_ip }}:{{ ghost_port }}"
          # -- Database
          - name: database__connection__database
            value: "{{ db_name }}"
          - name: database__connection__user
            value: "{{ db_user }}"
          - name: database__connection__password
            value: "{{ db_pass }}"
          - name: database__connection__host
            value: "mysql-service"
          - name: database__client
            value: "mysql"
          # -- Email  
          - name: mail__transport
            value: "SMTP"
          - name: mail__options__service
            value: "Mailgun"
          - name: mail__options__host
            value: "smtp.mailgun.org"
          - name: mail__options__port
            value: "465"
          - name: mail__options__auth__user
            value: "{{mail__options__auth__user}}"
          - name: mail__options__auth__pass
            value: "{{mail__options__auth__pass}}"
        ports:
        - containerPort: 2368