apiVersion: v1
kind: Service
metadata:
  namespace: "{{ ghost_namespace }}"
  name:  ghost-service
  labels:
    app: ghost
spec:
  type:  LoadBalancer
  selector:
    app: ghost
  ports:
    - protocol: TCP
      targetPort:  2368
      port:  {{ ghost_port }}