---
- name: Create ghost namespace
  kubernetes.core.k8s:
    state: present
    api_version: v1
    name: "{{ ghost_namespace }}"
    kind: Namespace
    wait: yes

- name: Create ghost service file
  template:
    src: ghost-service.yml
    dest: tmp/ghost-service.yml

- name: Start ghost service
  kubernetes.core.k8s:
    state: present
    src: tmp/ghost-service.yml
    wait: yes

- name: Get service ip and port
  kubernetes.core.k8s_info:
    kind: Service
    name: ghost-service
    namespace: "{{ ghost_namespace }}"
  register: ghost_service
  until: ghost_service.resources[0].status.loadBalancer.ingress is defined
  retries: 5
  delay: 30

- name: Define ghost ip and port
  set_fact:
    ghost_ip: "{{ ghost_service.resources[0].status.loadBalancer.ingress[0].ip }}"
    ghost_port: "{{ ghost_service.resources[0].spec.ports[0].port }}"

- name: Print ghost URL
  debug:
    msg: "Ghost url: http://{{ ghost_ip }}:{{ ghost_port }}"

- name: Create ghost deployment file
  template:
    src: ghost-deployment.yml
    dest: tmp/ghost-deployment.yml

- name: Deploy ghost app
  kubernetes.core.k8s:
    state: present
    src: tmp/ghost-deployment.yml
    wait: yes