---
- name: Get password hash
  shell: python3 -c 'import bcrypt; print(bcrypt.hashpw(b"{{ admin_pass }}", bcrypt.gensalt(rounds=10)).decode("ascii"))'
  register: output

- name: Get mysql pod
  k8s_info:
    kind: Pod
    namespace: "{{ db_namespace }}"
    label_selectors:
      - app=mysql
  register: mysql_pod

- name: Define pod name
  set_fact:
    mysql_pod_name: '{{ mysql_pod.resources[0].metadata.name }}'

- name: Wait for user to be created
  kubernetes.core.k8s_exec:
    namespace: "{{ db_namespace }}"
    pod: "{{ mysql_pod_name }}"
    command: 'mysql --user="{{ db_user }}" --password="{{ db_pass }}" -e "SELECT * FROM {{ db_name }}.users where id=1;"'
  register: migrations_result
  until: migrations_result.stdout != ""
  retries: 20
  delay: 10

- name: Update admin
  kubernetes.core.k8s_exec:
    namespace: "{{ db_namespace }}"
    pod: "{{ mysql_pod_name }}"
    command: 'mysql --user="{{ db_user }}" --password="{{ db_pass }}" -e "{{ populate_command }}"'
