kind: Service
apiVersion: v1
metadata:
  name:  mysql-service
  labels:
    app: mysql
    tier: db
spec:
  type:  ClusterIP
  selector:
    app:  mysql
  ports:
    - targetPort:  3306
      port:  3306