---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
    tier: db
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "true"
          - name: MYSQL_DATABASE
            value: "{{ db_name }}"
          - name: MYSQL_USER
            value: "{{ db_user }}"
          - name: MYSQL_PASSWORD
            value: "{{ db_pass }}" # Use Secret object in real usage
        ports:
          - containerPort: 3306
        volumeMounts:
          - name:  mysql-pv
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pv 
          persistentVolumeClaim:
            claimName: mysql-pv-claim