---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ db_namespace }}"
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi